apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: 381491839993.dkr.ecr.us-east-1.amazonaws.com/mac98aws:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: ecr-secret
      
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: springboot-app
    k8s-app: springboot-app
spec:
  type: NodePort
  selector:
    app: springboot-app  # Match this with your deployment labels
  ports:
    - protocol: TCP
      port: 80       # Service port inside the cluster
      targetPort: 8085  # Port on which the application runs inside the container
      nodePort: 30007 
    
