apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: 381491839993.dkr.ecr.us-east-1.amazonaws.com/mac98aws:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: ecr-secret
      
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
    name: springboot-app
spec:
  type: NodePort
  selector:
    app: springboot-app
  #- name: http
  ports: 
  - protocol: TCP
    port: 80       # Internal service port
    targetPort: 8080  # Port your app is running on inside the container
    nodePort: 30007 
    
